# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170312_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 18, 2, 13, 325585, tzinfo=utc)),
        ),
    ]
