# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170312_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activity_statuses',
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
