# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170312_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Activity'),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='users.Teacher'),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approver', to='users.Teacher'),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
